### ISSUE TITLE
Unignore vendor directory

### ISSUE THREAD

**Issue by MOZGIII** [ktr0731/evans#118]
I can't `go get` evans because the vendor directory is in `.gitignore`. It's supposed to be in the tree for `go get` to work.

**Comment by ktr0731** [comment]
Any errors occurred? I'm not going to include `vendor` directory to Git repository. (However, I'm planning Go modules support)

**Comment by MOZGIII** [comment]
Yes, it failed to install. `go get` does not take any version information into account. Code residing in `vendor` directory naturally gets picked up though. In that sense, `dep` is completely useless with stock `go get` if you don't include `vendor`, and requires extra step after cloning (running `dep ensure`).
In that sense installation instructions in the readme are *misleading*. You can't rely on vendoring tool while not including `vendor` and have `go get` work.

Modules support solve this, and, if you for some reason can't stand including `vendor` dir in the code - at least the code will really be `go get`-able.

This project seems to make a lot of choices of it's own, that are disconnected from the idiomatic ways things are done in go nowadays. Maybe it's ok in theory, but for me it only caused practical problems so far, so I can't say I like those deviations.

**Comment by ktr0731** [comment]
`README.md` says, 
> Highly recommended methods are GitHub Releases or Homebrew because these can be software update automatically by the built-in feature in Evans.

In this project, we are highly recommending to use GitHub Released binary or Homebrew package because I assume that Evans is used for general users, not only Gophers.

As you said, currently, vendoring is disabled at `go get`. So, we don't recommend to use `go get` to installation.
Instead of it, I'll add an installation which using Go modules. That's all.
