### ISSUE TITLE
Unable to send grpc-timeout header

### ISSUE THREAD

**Issue by thecodejunkie** [ktr0731/evans#291]
## Describe the bug
I was hoping to define a deadline, when calling a gRPC service using Evans, but was unable to find any support for it. So I thought I could attach the `grpc-timeout` header but it does not appear to work. I can define the header in Evans, but I am not seeing it when the call reaches my server

## To reproduce
Use `header grpc-timeout=2S" before calling an RPC. I've inspected my headers with `show headers` and it's correctly listed.

I wrote a tiny gRPC server and the following snippet was used to extract Deadline information + headers from the incoming context

```go
deadline, y := ctx.Deadline()
if y {
	fmt.Println(deadline)
}

data, ok := metadata.FromIncomingContext(ctx)
if ok {
	for k, v := range data {
		fmt.Println(k)

		for _, y := range v {
			fmt.Printf("\t%s\n", y)
		}
	}
}
```

I can see all other headers that I define, even ones with a hyphen in like `foo-bar=baz`

## Expected behavior
To be able to specify client deadlines when calling my gRPC server

## Environment
- OS: osx
- Terminal: oh-my-zsh
- Evans version: evans 0.9.0
- `protoc` version: libprotoc 3.11.4
- `protoc` plugin version (if you are using):

**Comment by ktr0731** [comment]
Thanks for reporting an issue. And I'm sorry for the late reply.

Yes, currently, Evans doesn't support timeout based on `grpc-timeout`. Also, we never use `grpc-timeout` header because it's revered [the gRPC library](https://github.com/grpc/grpc-go) that Evans depends.

The only way to implement timeout is by providing flags and specify it internally by using the higher-level API the library provides.

It's a necessary feature, but I don't have any time to implement it...

**Comment by taciomcosta** [comment]
Hi, @ktr0731 
can I take this one?

**Comment by ktr0731** [comment]
Hi, @taciomcosta 
Of course! Feel free to ask if you have any questions.
