### ISSUE TITLE
Request: support for fields of type Any

### ISSUE THREAD

**Issue by EricBuist** [ktr0731/evans#587]
Hi, I've been searching for a while and cannot find any information about whether Evans supports protobufs with fields of type Any or not. From my experiments, it seems that is not fully supported. No matter what type URI I give, Evans always complains the type is missing, even though I provided the protobuf on the command line, in addition to the protobuf of the main message type with the Any field. Documentation should indicate whether fields of type Any are supported and if yes, examples of working payloads with such fields.

**Comment by ktr0731** [comment]
Hi. Yes, currently, Evans supports Any messages partially. When using gRPC reflection, non well-known types shouldn't be work correctly. It's not the desirable behavior, and it's already reported as an issue, and now we are working on it.
We close this issue due to duplication. Thank you for reporting this issue.
